### ISSUE TITLE
How does this work with free for all games?

### ISSUE THREAD

**Issue by Pyrolistical** [openbracketformat/openbracketformat#1]
Current format bakes in an assumption there is only two entrants, as in `entrant1ID` and `entrant2ID`

**Comment by EddieDemon** [comment]
Has this been fixed since you raised the issue? I see that in the current spec it's an array.

**Comment by openbracketformat** [comment]
At this time, this format supports 'entity' vs 'entity' matches, so it would not support free-for-all or battle royale.
