### ISSUE TITLE
The "other" field breaks the concept of creating a standard

### ISSUE THREAD

**Issue by Pyrolistical** [openbracketformat/openbracketformat#10]
I understand the intent is to create a catch all in case this format misses anything, but these kinds of fields in standards tend to eat the whole. This will be abused to no end once people start relying on certain fields within the "other" field, it will usurp this entire endeavour

**Comment by RLHerbert** [comment]
Perhaps replace it with a simple "notes" field?

**Comment by VestboyMyst** [comment]
we'll cross that bridge when we get to it. and if there is a certain field that appears often in `other` we would ideally try to adopt it into the format itself
