### ISSUE TITLE
Representing team games

### ISSUE THREAD

**Issue by jack-bliss** [openbracketformat/openbracketformat#11]
Right now the schema seems to be built around 1v1 games - are there plans to include support for team games, or is it considered out of scope?

**Comment by VestboyMyst** [comment]
It would be great if we can figure out a way to handle arbitrary team sizes/numbers in the future. For now, we purposely generalized the concept of "players" to "entrants" so that team names could be used as `entrantIDs` 

Our initial thought was to add optional `entrant3ID` , `entrant4ID` (etc) fields, and then optional `entrantXTeam` fields for each of them. Do you foresee any problems with that implementation? Any other good ways we could do it?

**Comment by jack-bliss** [comment]
i think if you've already generalised "players" to "entrants", it makes sense to have the entrants be the team, rather than having separate entrants per player then a new team field to bundle them together. that way, once you're in the nitty-gritty of trying to render the bracket, you don't really care if its a team game or not. tweaking the entrant schema to include info about multiple players would be a great start, and i know theres some other discussion around the schema for character selection.

i guess there's a difference between "matches between entrants that are teams" and "matches with more than 2 entrants". for example, in smash, you could have 2v2 or 1v1v1v1, in either case there are 4 human players to describe (and potentially individually represent scores for?) but either 2 or 4 separate entrants.

the solution for the more-than-two-entrants problem of adding extra numbered entrants would do the trick on paper, but i don't think it scales well. some games could have up to 10 or 20 entrants per set, which is a lot of different fields, and it makes it hard to enumerate over all the participants in a set without doing some kinda sketchy meta-programming and hoping that everything is in the right place. you'd also need an extra field telling you how many entrants there were in the set.

having said that, an alternate solution like an array of entrants in the set makes it harder to quickly and easily access data in the very common two-entrant case.

**Comment by VestboyMyst** [comment]
This should now be addressed - an entrant can be a single player, or multiple players.

Also OBF is now being designed to handle only 1 entrant vs 1 entrant.
