### ISSUE TITLE
Representing progressions between phases rather than between matches

### ISSUE THREAD

**Issue by jack-bliss** [openbracketformat/openbracketformat#14]
For progression between elimination brackets, we can simply progress directly from one elimination match in one phase to an elimination match in another phase, and everything stays wired up. however, sometimes you progress from the standings of an entire bracket, for example when doing round robin into elimination. is this something OBF can/should capture explicitly?

**Comment by VestboyMyst** [comment]
As of now, we aren't going to capture this explicitly, but you can use the order of phases in the phase array to extrapolate the progression.
