### ISSUE TITLE
Consider adding support for group stages and leagues.

### ISSUE THREAD

**Issue by RLHerbert** [openbracketformat/openbracketformat#16]
Many tournaments are either the pinnacle to a group stage and/or league or lead into another tournament in the same league. It would be useful, though not required, to add support for representing group stages and leagues.

**Comment by Pyrolistical** [comment]
at that point where do you stop? do you represent the whole league in one document? how do you separate entrants from different parts of the league. like nhl conferences

**Comment by RLHerbert** [comment]
Leagues could be separated out into their own standard which uses OBF itself. I would say leagues are not a particularly high priority item, just something to keep in mind going forward and potentially support in the future.

**Comment by VestboyMyst** [comment]
For now at least, we've decided to focus OBF on capturing data from individual events instead of leagues. We might revisit this decision in the future.
