### ISSUE TITLE
Representing disqualifications?

### ISSUE THREAD

**Issue by jack-bliss** [openbracketformat/openbracketformat#9]
Hello!

Love the idea, as someone who has processed bracket data from multiple sources, this is very appealing!

I'm wondering if you have any plans to add support for disqualification? Right now you can represent them just as a normal win, perhaps doing something funky with the scores like -1, but it can be nice to show that this game was never actually played.

edit: also just saw someone else mention byes which i think comes under this same category!

**Comment by VestboyMyst** [comment]
Yes - adding options for DQ/Bye makes sense.

**Comment by jschnei** [comment]
See also the comments in #4. The current idea is to add some more options to `Set.status`, but if you have other ideas for how this should be recorded we're welcome to ideas.

**Comment by VestboyMyst** [comment]
We're adding 'DQ' to entrant1Result and entrant2Result to address this in the next version
